- name: custom .gitconfig
  ansible.builtin.shell: |
    if [ ! -e /root/.gitconfig ]; then
      {
        echo "[init]"
        echo "        defaultBranch = main"
        echo ""
        echo "[core]"
        echo "    pager = delta"
        echo "[interactive]"
        echo "    diffFilter = delta --color-only"
        echo "[delta]"
        echo "    navigate = true"
        echo "    line-numbers = true"
        echo "[merge]"
        echo "    conflictstyle = diff3"
        echo "[diff]"
        echo "    colorMoved = default"
      } | tee /root/.gitconfig
    fi
  args:
    executable: /bin/bash

- name: clone dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/pabloqpacin/dotfiles.git'
    dest: /root/dotfiles
    version: devel

- name: rename old .vimrc and create symlink
  ansible.builtin.shell: |
    if [ ! -L /root/.vimrc ]; then
      mv /root/.vimrc{,.bak}
      ln -s /root/dotfiles/.vimrc /root/.vimrc
    fi
  args:
    executable: /bin/bash

- name: ensure .config directory exists
  ansible.builtin.file:
    path: /root/.config
    state: directory
    mode: '0755'

- name: symlink bat
  ansible.builtin.file:
    src: /root/dotfiles/.config/bat
    dest: /root/.config/bat
    state: link
    force: no

- name: symlink lf
  ansible.builtin.file:
    src: /root/dotfiles/.config/lf
    dest: /root/.config/lf
    state: link
    force: no

- name: symlink tmux
  ansible.builtin.file:
    src: /root/dotfiles/.config/tmux
    dest: /root/.config/tmux
    state: link
    force: no

- name: Download and install Oh My Zsh
  ansible.builtin.shell: |
    if [ ! -d /root/.oh-my-zsh ]; then
      yes | sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    fi
  args:
    executable: /bin/bash
  environment:
    ZSH: "{{ ansible_env.HOME }}/.oh-my-zsh"
    RUNZSH: "no"
    KEEP_ZSHRC: "yes"

- name: Backup existing .zshrc if it exists
  ansible.builtin.shell: |
    if [ ! -L /root/.zshrc ]; then mv /root/.zshrc /root/.zshrc.bak; fi
  args:
    executable: /bin/bash

- name: Create symlink for .zshrc
  ansible.builtin.file:
    src: /root/dotfiles/.zshrc
    dest: /root/.zshrc
    state: link

- name: Execute zsh setup scripts
  ansible.builtin.shell: |
    {% for script in scripts %}
    bash {{ script }}
    {% endfor %}
  args:
    executable: /bin/bash
  vars:
    scripts:
      - /root/dotfiles/zsh/plugins/clone-em.sh
      - /root/dotfiles/scripts/setup/omz-msg_random_theme.sh

- name: Ensure zsh is the default shell
  ansible.builtin.user:
    name: root
    shell: /usr/bin/zsh
  become: true
